export const UPDATE_USERNAME = 'UPDATE_USERNAME';

export const WORKHOUSE_LOADING = 'WORKHOUSE_LOADING';
export const WORKHOUSE_FAILED = 'WORKHOUSE_FAILED';
export const ADD_WORKHOUSE = 'ADD_WORKHOUSE';
export const UPDATE_WORKHOUSE = 'UPDATE_WORKHOUSE'
export const ACTIVE_WORKHOUSE = 'ACTIVE_WORKHOUSE'
export const BLOCK_WORKHOUSE = 'BLOCK_WORKHOUSE'
export const REMOVED_WORKHOUSE = 'REMOVED_WORKHOUSE'

export const MACHINERY_LOADING = 'MACHINERY_LOADING';
export const MACHINERY_FAILED = 'MACHINERY_FAILED';
export const ADD_MACHINERY = 'ADD_MACHINERY';
export const UPDATE_MACHINERY = 'UPDATE_MACHINERY'
export const ACTIVE_MACHINERY = 'ACTIVE_MACHINERY'
export const BLOCK_MACHINERY = 'BLOCK_MACHINERY'
export const REMOVED_MACHINERY = 'REMOVED_MACHINERY'