export const UPDATE_USERNAME = 'UPDATE_USERNAME';

export const WORKHOUSE_LOADING = 'WORKHOUSE_LOADING';
export const WORKHOUSE_FAILED = 'WORKHOUSE_FAILED';
export const ADD_WORKHOUSE = 'ADD_WORKHOUSE';
export const UPDATE_WORKHOUSE = 'UPDATE_WORKHOUSE'
export const ACTIVE_WORKHOUSE = 'ACTIVE_WORKHOUSE'
export const BLOCK_WORKHOUSE = 'BLOCK_WORKHOUSE'
export const REMOVED_WORKHOUSE = 'REMOVED_WORKHOUSE'
