export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const WORKHOUSE_LOADING = 'WORKHOUSE_LOADING';
export const WORKHOUSE_FAILED = 'WORKHOUSE_FAILED';
export const ADD_WORKHOUSE = 'ADD_WORKHOUSE';